### ISSUE TITLE
Enable to use custom docker and rkt containers as benchmark units

### ISSUE THREAD

**Issue by hectorj2f** [giantswarm/nomi#10]
We want to enable users to define which containers to use when running a benchmark that makes use of `rkt` or `docker` with Nomi. A generic mechanism of notification + keep alive should be needed to support such a feature.

**Comment by hectorj2f** [comment]
ping @giantswarm/team-core

**Comment by pmoust** [comment]
very interested in this

**Comment by hectorj2f** [comment]
Thanks @pmoust. We plan to add this feature very soon. :)

**Comment by hectorj2f** [comment]
This issue has been addresed in https://github.com/giantswarm/nomi/issues/18
