### ISSUE TITLE
Allow submission of custom fleet systemd units and timers

### ISSUE THREAD

**Issue by pmoust** [giantswarm/nomi#14]
Benchmark complex fleet units and timers
- [x] Add support to use custom a fleet unit service
- [ ]  Add support to use a group of fleet units and timers

**Comment by hectorj2f** [comment]
Thanks @pmoust. Could you elaborate a bit more your scenario ? We plan to allow users to submit their custom fleet units, but what about the timers?

**Comment by pmoust** [comment]
We have a lot of timers that tigger systemd services, those timers hit etcd hard or do long polling via etcd-watch.

This affects etcd (and therefore fleet) performance.

I would love to be able to properly benchmark this with Nomi

**Comment by hectorj2f** [comment]
So, you'd be interested on analyzing the behavior of etcd/fleet when running those timers. Good!! I will keep this in mind when adding the support for custom fleet units. :dancer: 

By the way, you seem concern with the performance and reliability of fleet, you might have a look at this PR (https://github.com/coreos/fleet/pull/1426). We're planning to improve the performance and scalability of fleet. +1 are always welcomed :dart:
