### ISSUE TITLE
enh: Add option to simulate failure in a HA setting

### ISSUE THREAD

**Issue by pmoust** [giantswarm/nomi#15]
In Chaos-Monkey style, introduce random failure options to benchmark fleet/etcd behavior.

Use-case: I need to benchmark fleet performance in split-brain scenarios (ex. losing an availability zone) or during raft elections of a new leader upon a node failure, or at times of unreliable networking.

**Comment by pmoust** [comment]
Ref: Neflix SimianArmy https://github.com/Netflix/SimianArmy/wiki/Chaos-Monkey

**Comment by hectorj2f** [comment]
@pmoust Apologize for my delayed reply. It seems a good add-ons but I believe this functionality should be covered by a different, but not independent, tool. Anyway, I'd keep you up to date with any decision regarding this functionality.

**Comment by pmoust** [comment]
Fleet is no longer maintained, closing this.
